### ISSUE TITLE
회원 가입 구현

### ISSUE THREAD

**Issue by MorganJH-Kim** [Morgan-Jackson-Kim/RamenRecipeBook#2]
- [x] DB 테이블 생성
- [x] view 컨트롤러 생성
- [x] 회원가입 기능 구현
- [x] 비밀번호 암호화
- [x] 회원가입 페이지 구현

**Comment by MorganJH-Kim** [comment]
회원가입 페이지 구현 중 get mapping 이 적용되지 않는 이슈
1.application.yml 이 문제인가?
2.DB config 경로가 잘못되었는가?
3.controller , requestmapping 이 적용되지 않았는가?
4.src/main/webapp/WEB-INF/jsp/user 경로가 잘못되었는가
5.gradle 세팅이 안되었는가

**Comment by MorganJH-Kim** [comment]
1.application.yml 이 문제인가?
application properties 에서 aplication.yml로 변경했었었음

```
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ramenrecipebook?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

logging:
  level:
    root: info
```
하지만 문제가 없었음
